export const text = {
  th: {
    title: "ประเมินเบื้องต้น ข้อมูลพื้นฐานเพื่อพิจารณาความเป็นไปได้",
    projectInfo: "ข้อมูลโครงการ",
    projectName: "ชื่อโครงการ",
    projectNamePlaceholder: "โปรดกรอกชื่อโครงการ...",
    projectOwnerName: "เจ้าของโครงการ",
    projectOwnerNamePlaceholder: "โปรดกรอกชื่อเจ้าของโครงการ",
    location: "สถานที่",
    locationPlaceholder: "โปรดกรอกสถานที่...",
    client: "ลูกค้า",
    clientPlaceholder: "โปรดกรอกชื่อลูกค้า...",
    documentDate: "วันที่ออกเอกสาร",
    duration: "กำหนดระยะเวลาการดำเนินงาน (วัน)",
    description: "รายละเอียดโครงการเพิ่มเติม",
    descriptionPlaceholder: "โปรดกรอกรายละเอียดโครงการเพิ่มเติม...",
    createProject: "สร้างโครงการ",
    taskManagement: "กำหนดระยะเวลาการดำเนินงาน (วัน)",
    addTask: "เพิ่มหัวข้อ",
    newTaskPlaceholder: "โปรดกรอกชื่อหัวข้อใหม่...",
    daysPlaceholder: "จำนวนวัน",
    add: "เพิ่ม",
    cancel: "ยกเลิก",
    days: "วัน",
    selectTasks: "เลือกงานเพื่อสรุประยะเวลา",
    serviceSelection: "เลือกรายละเอียดบริการ",
    totalDays: "ระยะเวลาการทำงานรวม",
    calculated: "(คำนวณจากงานที่เลือก)",
    downloadPDF: "ดาวน์โหลดรายการสรุป (PDF)",
    creating: "กำลังสร้าง PDF...",
    ready: "ดาวน์โหลด PDF พร้อมแล้ว!",
  },
  en: {
    title: "Preliminary Assessment",
    projectInfo: "Project Information",
    projectName: "Project Name",
    projectNamePlaceholder: "Please enter project name...",
    projectOwnerName: "Project Owner",
    projectOwnerNamePlaceholder: "Please enter project owner...",
    location: "Location",
    locationPlaceholder: "Please enter location...",
    client: "Customer",
    clientPlaceholder: "Please enter customer name...",
    documentDate: "Document Date",
    duration: "Project Duration (days)",
    description: "Additional Project Details",
    descriptionPlaceholder: "Additional project details...",
    createProject: "Create Project",
    taskManagement: "Project Duration (days)",
    addTask: "Add Task",
    newTaskPlaceholder: "Please enter new task name...",
    daysPlaceholder: "Please enter number of days...",
    add: "Add",
    cancel: "Cancel",
    days: "days",
    selectTasks: "Select tasks to summarize duration",
    serviceSelection: "Select Service Details",
    totalDays: "Total Working Duration",
    calculated: "(Calculated from selected tasks)",
    downloadPDF: "Download Summary (PDF)",
    creating: "Generating PDF...",
    ready: "PDF is ready for download!",
  },
};
